### ISSUE TITLE
Unexpected declaration? Maybe opts elsewhere?

### ISSUE THREAD

**Issue by b7s9** [wkdu/playlist-scraper#1]
```
$ node scraper --end 47453 --start 47400 --format csv
/Users/finch/Desktop/programming/wkdu/playlist-scraper/playlist-scraper/node_modules/csv-stringify/lib/index.js:86
Stringifier = function(opts = {}) {
                            ^
```

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/finch/Desktop/programming/wkdu/playlist-scraper/playlist-scraper/scraper.js:7:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by pll33** [comment]
What version Node.js are you using?

**Comment by pll33** [comment]
Reason for closing issue: unsupported Node.js version
